### ISSUE TITLE
Weird paths in archive 

### ISSUE THREAD

**Issue by Suor** [jcsato/sato_balance_mod#1]
It might not affect the game but the files in the release archive are not really arranged into dirs but have paths containing `\` instead
![sato-balance-weird-paths](https://github.com/jcsato/sato_balance_mod/assets/284103/e11bd4b0-86a6-4a89-990e-bf1847fbf3eb)

**Comment by jcsato** [comment]
Sorry for just responding now, it's been. . .some kind of fall.

WOMM: 
![image](https://github.com/jcsato/sato_balance_mod/assets/77210861/a130fe96-2ff8-444e-99f9-7636aca623f0)

Maybe it's something off w/ Ark? Feel free to reopen if you see other weirdness here.
